---
name: Autolabeler

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  autolabeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Release Drafer Autolabeler
      uses: release-drafter/release-drafter@v5
      with:
        disable-releaser: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}